databases:
  - name: udadoctors-db
    databaseName: udadoctors
    user: udadoctors
    plan: free

services:
  - type: web
    name: udadoctors
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: udadoctors-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false   # You'll paste this manually in Render dashboard
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
